<?php

use Illuminate\Support\Str;
/**
 * @author ALI MOUSSA Moussa <admin@mayottesport.com>
 * @copyright 2020 ALI MOUSSA Moussa
 * @license MIT
 */

// On insère les crud_tables
$crudTables = [
    [1, 'sports', 1, 'nom'],
    [2, 'competitions', 1, 'nom'],
    [4, 'baremes', 1, 'nom'],
    [5, 'equipes', 1, 'nom'],
    [6, 'saisons', 1, 'competition_id'],
    [7, 'crud_tables', 1, 'nom'],
    [8, 'crud_attributs', 1, 'crud_table_id'],
    [9, 'modifs', 1, 'match_id'],
    [10, 'users', 1, 'pseudo'],
    [11, 'villes', 1, 'nom'],
    [12, 'journees', 1, 'saison_id'],
    [13, 'matches', 0, 'journee_id'],
    [14, 'terrains', 1, 'nom'],
    [15, 'crud_attribut_infos', 1, 'crud_attribut_id'],
    [16, 'roles', 1, 'nom'],
    [17, 'regions', 1, 'nom'],
    [27, 'failed_jobs', 0, NULL],
    [28, 'migrations', 0, NULL],
    [30, 'password_resets', 0, NULL],
    [31, 'bareme_infos', 1, 'bareme_id'],
    [32, 'match_infos', 0, 'match_id'],
    [34, 'equipe_saison', 1, 'saison_id'],
    [39, 'jobs', 0, NULL],
    [40, 'articles', 1, NULL]
];
foreach ($crudTables as $donnees) {
    $crudTable = new App\CrudTable([
        'id' => $donnees[0],
        'nom' => $donnees[1],
        'slug' => Str::slug($donnees[1]),
        'crudable' => $donnees[2],
        'tri_defaut' => $donnees[3]
    ]);
    $crudTable->save();
}

// On insère les crud_attributs
$crudAttributs = [
    [1, 1, 'nom', 'Sport', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Sport</span> doit contenir entre 3 et 50 caractères.'],
    [3, 2, 'nom', 'Nom', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Nom</span> doit contenir entre 3 et 50 caractères.'],
    [4, 2, 'sport_id', 'Sport', 1, NULL, 'Merci de sélectionner un <span class=\'text-danger font-italic\'>Sport</span>.'],
    [6, 4, 'nom', 'Barème', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Barème</span> est obligatoire et doit contenir entre 3 et 50 caractères.'],
    [7, 4, 'sport_id', 'Sport', 1, NULL, 'Veuillez faire un choix de <span class=\'text-danger font-italic\'>Sport</span>'],
    [8, 2, 'nom_complet', 'Nom complet', NULL, 1, NULL],
    [9, 5, 'nom', 'Équipe', NULL, NULL, 'Le champ <span class=\'text-danger font-italic\'>Équipe</span> est obligatoire et doit contenir entre 3 et 50 caractères.'],
    [10, 5, 'sport_id', 'Sport', 1, 0, NULL],
    [13, 1, 'created_at', 'Créé le', NULL, NULL, NULL],
    [14, 1, 'updated_at', 'Mis à jour le', NULL, NULL, NULL],
    [15, 4, 'victoire', 'Victoire', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Victoire</span> doit être inclus entre 0 et 30.'],
    [16, 4, 'nul', 'Nul', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Nul</span> est optionnel. S\'il est rempli, il doit être inclus entre 0 et 30 compris.'],
    [17, 4, 'defaite', 'Défaite', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Défaite</span> doit être inclus entre 0 et 30.'],
    [18, 8, 'attribut', 'Attribut', NULL, NULL, 'Le champ <span class=\'text-danger font-italic\'>Attribut</span> est obligatoire et doit contenir entre 3 et 50 caractères.'],
    [19, 8, 'crud_table_id', 'Table', 7, NULL, 'Veuillez faire un choix de <span class=\'text-danger font-italic\'>Table</span>'],
    [22, 8, 'attribut_crud_table_id', 'Table de réference de l\'attribut', 7, 1, NULL],
    [23, 8, 'label', 'Label à afficher pour l\'attribut', NULL, NULL, NULL],
    [27, 6, 'competition_id', 'Compétition', 2, 0, NULL],
    [28, 6, 'annee_debut', 'Début', NULL, 0, 'Veuillez saisir une année de <span class=\'text-danger font-italic\'>Début</span> .'],
    [29, 6, 'annee_fin', 'Fin', NULL, 0, 'Veuillez saisir une année de <span class=\'text-danger font-italic\'>Fin</span>.'],
    [32, 8, 'optionnel', 'Champ optionnel ?', NULL, 1, NULL],
    [35, 8, 'data_msg', 'Message d\'erreur', NULL, 1, NULL],
    [39, 5, 'nom_complet', 'Nom complet', NULL, 1, 'Le <span class=\'text-danger font-italic\'>Nom complet</span> est optionnel. S\'il est rempli, il doit comporter entre 3 et 50 caractères.'],
    [40, 5, 'feminine', 'Féminine?', NULL, NULL, NULL],
    [41, 5, 'non_mahoraise', 'Non mahoraise?', NULL, NULL, NULL],
    [45, 12, 'saison_id', 'Saison', 6, 0, 'Veuillez faire un choix de <span class=\'text-danger font-italic\'>Saison</span>'],
    [46, 12, 'numero', 'Journée', NULL, 0, NULL],
    [47, 12, 'date', 'Date', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Date</span> est optionnel. S\'il est rempli, il doit contenir une date valide.'],
    [48, 6, 'nb_journees', 'Nombre de journées', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Nombre de journées</span> est obligatoire. Il doit être compris entre 1 et 100.'],
    [49, 13, 'journee_id', 'Journée', 12, 0, 'Veuillez sélectionner une <span class=\'text-danger font-italic\'>Journée</span>.'],
    [50, 13, 'equipe_id_dom', 'Equipe dom.', 5, 0, 'Veuillez faire un choix d\'<span class=\'text-danger font-italic\'>Equipe dom.</span>'],
    [51, 13, 'equipe_id_ext', 'Equipe ext.', 5, 0, 'Veuillez faire un choix d\'<span class=\'text-danger font-italic\'>Equipe ext.</span>'],
    [52, 6, 'bareme_id', 'Barème', 4, 1, NULL],
    [53, 14, 'nom', 'Nom', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Nom</span> est obligatoire et  doit comporter entre 3 et 50 caractères.'],
    [54, 14, 'ville_id', 'Ville', 11, 0, 'Veuillez sélectionner une <span class=\'text-danger font-italic\'>Ville</span>.'],
    [55, 11, 'nom', 'Ville', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Ville</span> est obligatoire et doit comporter entre 3 et 50 caractères.'],
    [58, 13, 'date', 'Date', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Date</span> et optionnel. Il doit contenir une date valide s\'il est rempli.'],
    [59, 13, 'heure', 'Heure', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Heure</span> doit contenir une heure valide s\'il est rempli. Format HH:MM ou HH:MM:SS.'],
    [60, 13, 'terrain_id', 'Terrain', 14, 1, 'Veuillez sélectionner un <span class=\'text-danger font-italic\'>Terrain</span>.'],
    [61, 15, 'crud_attribut_id', 'Attribut', 8, 0, 'Veuillez sélectionner un <span class=\'text-danger font-italic\'>Attribut</span>.'],
    [62, 15, 'propriete_id', 'Propriété', NULL, 0, 'Veuillez sélectionner une <span class=\'text-danger font-italic\'>Propriété</span>.'],
    [63, 15, 'valeur', 'Valeur', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Valeur</span> est obligatoire.'],
    [64, 10, 'name', 'Nom', NULL, 0, 'Le <span class=\'text-danger font-italic\'>Nom</span> est obligatoire.'],
    [65, 10, 'first_name', 'Prénom', NULL, 1, 'Le <span class=\'text-danger font-italic\'>Prénom</span> est optionnel. S\'il est rempli, il doit comporter entre 3 et 50 caractères.'],
    [66, 10, 'pseudo', 'Pseudo', NULL, 0, 'Le <span class=\'text-danger font-italic\'>Pseudo</span> est obligatoire et doit comporter entre 3 et 50 caractères.'],
    [67, 10, 'email', 'Email', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Email</span> est obligatoire.'],
    [69, 10, 'role_id', 'Rôle', 16, 0, 'Veuillez sélectionner un <span class=\'text-danger font-italic\'>Rôle</span>.'],
    [70, 10, 'region_id', 'Région', 17, 0, 'Veuillez sélectionner une <span class=\'text-danger font-italic\'>Région</span>.'],
    [71, 10, 'created_at', 'Ajouté le', NULL, 0, NULL],
    [72, 10, 'updated_at', 'Modifié le', NULL, 0, NULL],
    [74, 13, 'score_eq_dom', 'Score (équipe dom.)', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Score (dom.)</span> est optionnel.'],
    [75, 13, 'score_eq_ext', 'Score (équipe ext.)', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Score (ext.)</span> est optionnel.'],
    [76, 13, 'nb_modifs', 'Nombre de modifs', NULL, 0, NULL],
    [77, 13, 'acces_bloque', 'Accès bloqué', NULL, 0, NULL],
    [80, 7, 'nom', 'Nom', NULL, 0, NULL],
    [81, 7, 'tri_defaut', 'OrderBy par défaut', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Order by</span> ne peut dépasser 50 caractères.'],
    [82, 7, 'crudable', 'Crudable', NULL, 1, NULL],
    [83, 2, 'type', 'Type', NULL, 0, 'Veuillez sélectionner un <span class=\'text-danger font-italic\'>Type</span> de compétition.'],
    [84, 13, 'nom', 'Rencontre', NULL, 0, NULL],
    [90, 34, 'equipe_id', 'Equipe', 5, NULL, 'Veuillez sélectionner une <span class=\'text-danger font-italic\'>Equipe</span>.'],
    [91, 34, 'saison_id', 'Saison', 6, NULL, 'Veuillez sélectionner une <span class=\'text-danger font-italic\'>Saison</span>.'],
    [92, 12, 'type', 'Type', NULL, 1, NULL],
    [93, 2, 'home_position', 'Position page d\'accueil', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Position (accueil)</span> doit être supérieur à 0'],
    [94, 2, 'index_position', 'Position page Index sport', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Position (index)</span> doit être supérieur à 0 ou vide'],
    [95, 1, 'home_position', 'Position page d\'accueil', NULL, 1, 'Le champ <span class=\'text-danger font-italic\'>Position (accueil)</span> doit être supérieur à 0'],
    [96, 13, 'uniqid', 'Uniqid', NULL, 0, NULL],
    [97, 5, 'ville_id', 'Ville', 11, 0, 'Veuillez sélectionner une <span class=\'text-danger font-italic\'>Ville</span>.'],
    [98, 16, 'nom', 'Nom', NULL, 0, 'Le champ <span class=\'text-danger font-italic\'>Nom</span> doit contenir au moins 3 caractères.'],
    [99, 6, 'finie', 'Terminée', NULL, 1, NULL],
    [100, 31, 'bareme_id', 'Barème', 4, 0, 'Veuillez sélectionner un <span class=\'text-danger font-italic\'>Barème</span>'],
    [101, 31, 'propriete_id', 'Propriété', NULL, 0, 'Veuillez sélectionner une <span class=\'text-danger font-italic\'>Propriété</span>'],
    [102, 31, 'valeur', 'Valeur', NULL, 1, NULL],
    [103, 9, 'match_id', 'Match', 13, 0, NULL],
    [104, 9, 'user_id', 'Membre', 10, 0, NULL],
    [105, 9, 'note', 'Note', NULL, 0, NULL],
    [106, 9, 'type', 'Type', NULL, 0, NULL],
    [107, 17, 'nom', 'Nom', NULL, 0, 'Le <span class=\'text-danger font-italic\'>Nom</span> doit comporter au moins 3 caractères'],
    [108, 40, 'nom', 'Article', NULL, 0, NULL],
    [109, 40, 'titre', 'Titre', NULL, 0, 'Le <span class=\'text-danger font-italic\'>Titre</span> est obligatoire.'],
    [111, 40, 'img', 'Image', NULL, 1, NULL],
    [112, 40, 'valide', 'Validé', NULL, 0, NULL]
];

foreach ($crudAttributs as $donnees) {
    $crudAttribut = new App\CrudAttribut([
        'id' => $donnees[0],
        'crud_table_id' => $donnees[1],
        'attribut' => $donnees[2],
        'label' => $donnees[3],
        'attribut_crud_table_id' => $donnees[4],
        'optionnel' => $donnees[5],
        'data_msg' => $donnees[6]
    ]);
    $crudAttribut->save();
}

// On insère les crud_attribut_infos
$crudAttributInfos = [
    [8, 2, '3'],
    [1, 2, '1'],
    [3, 2, '1'],
    [4, 2, '2'],
    [6, 2, '1'],
    [7, 2, '2'],
    [9, 2, '1'],
    [10, 2, '2'],
    [13, 2, '3'],
    [14, 2, '4'],
    [15, 2, '3'],
    [16, 2, '4'],
    [17, 2, '6'],
    [18, 2, '2'],
    [19, 2, '1'],
    [22, 2, '3'],
    [23, 2, '4'],
    [27, 2, '1'],
    [28, 2, '2'],
    [29, 2, '3'],
    [32, 2, '5'],
    [35, 2, '6'],
    [39, 2, '4'],
    [40, 2, '5'],
    [41, 2, '6'],
    [45, 2, '1'],
    [46, 2, '2'],
    [47, 2, '4'],
    [48, 2, '4'],
    [49, 2, '1'],
    [50, 2, '2'],
    [51, 2, '5'],
    [52, 2, '2'],
    [53, 2, '1'],
    [54, 2, '2'],
    [55, 2, '1'],
    [58, 2, '6'],
    [59, 2, '7'],
    [60, 2, '8'],
    [1, 3, '1'],
    [3, 3, '1'],
    [4, 3, '2'],
    [6, 3, '1'],
    [7, 3, '2'],
    [8, 3, '3'],
    [9, 3, '1'],
    [10, 3, '2'],
    [15, 3, '3'],
    [16, 3, '4'],
    [17, 3, '6'],
    [18, 3, '2'],
    [19, 3, '1'],
    [22, 3, '3'],
    [23, 3, '4'],
    [27, 3, '1'],
    [28, 3, '2'],
    [29, 3, '3'],
    [32, 3, '5'],
    [35, 3, '6'],
    [39, 3, '4'],
    [40, 3, '5'],
    [41, 3, '6'],
    [45, 3, '1'],
    [46, 3, '2'],
    [47, 3, '4'],
    [48, 3, '4'],
    [49, 3, '1'],
    [50, 3, '2'],
    [51, 3, '5'],
    [52, 3, '2'],
    [53, 3, '1'],
    [54, 3, '2'],
    [55, 3, '1'],
    [58, 3, '6'],
    [59, 3, '7'],
    [60, 3, '8'],
    [15, 4, 'number'],
    [16, 4, 'number'],
    [17, 4, 'number'],
    [28, 4, 'number'],
    [29, 4, 'number'],
    [32, 4, 'checkbox'],
    [35, 4, 'textarea'],
    [40, 4, 'checkbox'],
    [41, 4, 'checkbox'],
    [46, 4, 'number'],
    [47, 4, 'date'],
    [48, 4, 'number'],
    [58, 4, 'date'],
    [15, 6, '0'],
    [16, 6, '0'],
    [17, 6, '0'],
    [28, 6, '1980'],
    [29, 6, '1980'],
    [46, 6, '1'],
    [48, 6, '1'],
    [15, 7, '30'],
    [16, 7, '30'],
    [17, 7, '30'],
    [28, 7, '3000'],
    [29, 7, '3000'],
    [48, 7, '100'],
    [6, 5, '.{3,50}'],
    [9, 5, '.{3,50}'],
    [18, 5, '.{3,50}'],
    [23, 5, '.{3,50}'],
    [39, 5, '.{3,50}'],
    [53, 5, '.{3,50}'],
    [55, 5, '.{3,50}'],
    [61, 2, '1'],
    [61, 3, '1'],
    [62, 2, '2'],
    [62, 3, '2'],
    [63, 2, '3'],
    [63, 3, '3'],
    [64, 2, '1'],
    [64, 3, '1'],
    [65, 2, '2'],
    [65, 3, '2'],
    [66, 2, '3'],
    [66, 3, '3'],
    [67, 2, '4'],
    [67, 3, '4'],
    [69, 2, '6'],
    [69, 3, '7'],
    [70, 2, '7'],
    [70, 3, '8'],
    [71, 2, '8'],
    [72, 2, '9'],
    [74, 2, '3'],
    [75, 2, '4'],
    [74, 3, '3'],
    [75, 3, '4'],
    [76, 2, '9'],
    [77, 2, '10'],
    [77, 3, '9'],
    [77, 4, 'checkbox'],
    [59, 4, 'time'],
    [82, 4, 'checkbox'],
    [80, 2, '1'],
    [80, 3, '1'],
    [81, 2, '2'],
    [81, 3, '2'],
    [82, 2, '3'],
    [82, 3, '3'],
    [83, 4, 'select'],
    [83, 3, '4'],
    [83, 8, 'type-competition'],
    [83, 2, '4'],
    [62, 4, 'select'],
    [62, 8, 'proprietes-crud-attributs'],
    [90, 2, '1'],
    [90, 3, '1'],
    [91, 2, '2'],
    [91, 3, '2'],
    [92, 2, '3'],
    [92, 3, '3'],
    [92, 8, 'journees'],
    [92, 4, 'select'],
    [93, 2, '5'],
    [94, 2, '6'],
    [93, 3, '5'],
    [94, 3, '6'],
    [93, 4, 'number'],
    [94, 4, 'number'],
    [95, 2, '2'],
    [95, 3, '2'],
    [95, 4, 'number'],
    [1, 1, '1'],
    [3, 1, '2'],
    [4, 1, '2'],
    [6, 1, '1'],
    [7, 1, '2'],
    [9, 1, '1'],
    [10, 1, '2'],
    [18, 1, '2'],
    [19, 1, '1'],
    [27, 1, '1'],
    [28, 1, '2'],
    [29, 1, '3'],
    [45, 1, '1'],
    [46, 1, '2'],
    [53, 1, '1'],
    [54, 1, '2'],
    [55, 1, '1'],
    [61, 1, '1'],
    [62, 1, '2'],
    [63, 1, '3'],
    [64, 1, '1'],
    [66, 1, '2'],
    [80, 1, '1'],
    [84, 1, '2'],
    [96, 1, '1'],
    [96, 2, '1'],
    [97, 2, '6'],
    [97, 3, '6'],
    [98, 1, '1'],
    [1, 5, '.{3,50}'],
    [3, 5, '.{3,50}'],
    [99, 2, '6'],
    [99, 3, '6'],
    [99, 4, 'checkbox'],
    [99, 1, '3'],
    [91, 1, '1'],
    [90, 1, '2'],
    [100, 1, '1'],
    [100, 2, '1'],
    [100, 3, '1'],
    [101, 1, '2'],
    [101, 2, '2'],
    [101, 3, '2'],
    [101, 4, 'select'],
    [101, 8, 'proprietes-baremes'],
    [102, 1, '3'],
    [102, 2, '3'],
    [102, 3, '3'],
    [103, 1, '1'],
    [103, 2, '1'],
    [104, 1, '2'],
    [104, 2, '2'],
    [105, 2, '4'],
    [106, 1, '3'],
    [106, 2, '3'],
    [106, 4, 'select'],
    [106, 8, 'types-modifs'],
    [107, 1, '1'],
    [107, 2, '1'],
    [107, 3, '1'],
    [108, 1, '1'],
    [109, 2, '1'],
    [109, 3, '1'],
    [111, 2, '2'],
    [111, 3, '2'],
    [112, 2, '3'],
    [112, 3, '3'],
    [112, 4, 'checkbox']
];
foreach ($crudAttributInfos as $donnees) {
    $crudAttributInfo = new App\CrudAttributInfo([
        'crud_attribut_id' => $donnees[0],
        'propriete_id' => $donnees[1],
        'valeur' => $donnees[2]
    ]);
    $crudAttributInfo->save();
}
